---
title: "mtgetl"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get data from MTG API

Require necessary packages

```{r}
require(jsonlite)
require(tidyverse)
require(curl)
```
 
establish authentication crendentials
```{r}
user <- Sys.getenv("TCG_PUBLIC")
key <- Sys.getenv("TCG_PRIVATE")
body = paste("grant_type=client_credentials&client_id=",user,"&client_secret=",key,sep="")

token <- httr::POST(url = "https://api.tcgplayer.com/token",
           body = body,
           httr::add_headers("application/x-www-form-urlencoded"))

token.content <- httr::content(token)
token <- token.content[1]
bearer <- toString(token)

token.content

auth.header <- paste("Authorization: bearer",bearer)

```


set tcg GET curl handle
```{r}
h <- new_handle()
handle_setheaders(h,"Authorization" = paste("bearer",bearer),"")
```

get categories table, turn it into a tibble 

```{r}
categories <- curl_fetch_memory("https://api.tcgplayer.com/catalog/categories?limit=1000", handle = h)

char.categories <- rawToChar(categories$content)
categories.data <- fromJSON(char.categories, simplifyDataFrame = TRUE, flatten = FALSE)
categories.tibble <- as_tibble(categories.data[[3]])
categories.tibble

```

Great! Now we have a list of category IDs that are related to MTG (1) - let's use that value to get the rest of the data we want. 

```{r}


groups.url <- "https://api.tcgplayer.com/catalog/categories/1/groups?limit=2000"
groups <- curl_fetch_memory(groups.url, handle = h)
char.groups <- rawToChar(groups$content)
groups.data <- fromJSON(char.groups,simplifyDataFrame = TRUE, flatten = TRUE)

# These are actually magic sets so we will name them that way

sets.tibble <- as_tibble(groups.data[[4]])
sets.tibble

```
